# Generated by Django 3.2 on 2021-04-21 11:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=50)),
                ('father_name', models.CharField(max_length=50)),
                ('date_of_birth', models.DateField(validators=[django.core.validators.MaxValueValidator(10)])),
                ('address', models.TextField(max_length=200)),
                ('city', models.CharField(max_length=30)),
                ('state', models.CharField(max_length=30)),
                ('pin', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(9956)])),
                ('phone_number', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(9999999999)])),
                ('email', models.EmailField(max_length=54)),
                ('class_opted', models.IntegerField()),
                ('marks', models.IntegerField()),
                ('date_enrolled', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
